// /src/lib/firebase.ts
// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
// To obtain a new config, running the "Get Firebase Config" command from the command palette.

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getAuth} from 'firebase/auth';
import {getFirestore} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyBwfoz1b3GfuVMhr9smJUcgzNuda13B0v8",
  authDomain: "claritas-copilot.firebaseapp.com",
  projectId: "claritas-copilot",
  storageBucket: "claritas-copilot.appspot.com",
  messagingSenderId: "1025750986126",
  appId: "1:1025750986126:web:32e60c121e39489f4308df"
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export {app, auth, db};
