
import type { RobotStrategy } from "@/ai/flows/strategy-council-flow.types";

// This file contains the pre-defined, local configuration for the 22 robot analysts.
// This approach removes the need for an AI call to build the council, making it faster and more reliable.

export const initialCouncilStrategies: Omit<RobotStrategy, 'suggestedStake' | 'suggestedDuration' | 'suggestedDurationUnit'>[] = [
  // --- Momentum & Trend ---
  {
    id: "RSI_BOT_1",
    strategyType: "RSI",
    justification: "Parâmetros de RSI médios (10) para divergências.",
    strongConfidence: 90,
    weakConfidence: 60,
    period: 10,
    strongBuyThreshold: 25,
    weakBuyThreshold: 35,
    strongSellThreshold: 75,
    weakSellThreshold: 65,
  },
  {
    id: "STOCH_BOT_1",
    strategyType: "STOCHASTIC",
    justification: "Estocástico padrão (14) para zonas de sobrecompra/venda.",
    strongConfidence: 90,
    weakConfidence: 70,
    period: 14,
    strongBuyThreshold: 20,
    weakBuyThreshold: 30,
    strongSellThreshold: 80,
    weakSellThreshold: 70,
  },
  {
    id: "MACD_BOT_1",
    strategyType: "MACD_CROSS",
    justification: "MACD padrão (12/26/9) para capturar tendências.",
    strongConfidence: 80,
    weakConfidence: 50,
    fastPeriod: 12,
    slowPeriod: 26,
    signalPeriod: 9,
  },
  {
    id: "ADX_BOT_1",
    strategyType: "ADX_TREND",
    justification: "Usa o ADX para confirmar a força da tendência antes de entrar.",
    strongConfidence: 85,
    weakConfidence: 60,
    period: 14,
    trendStrengthThreshold: 25,
  },
  {
    id: "AWESOME_OSC_BOT_1",
    strategyType: "AWESOME_OSCILLATOR",
    justification: "Busca 'pires' e cruzamentos de linha zero para sinais de momentum.",
    strongConfidence: 75,
    weakConfidence: 50,
  },
  {
    id: "TRIX_BOT_1",
    strategyType: "TRIX",
    justification: "Usa a inclinação do TRIX para um sinal de momentum suave.",
    strongConfidence: 70,
    weakConfidence: 45,
    period: 15,
  },
  {
    id: "ROC_BOT_1",
    strategyType: "ROC",
    justification: "Mede a velocidade da mudança de preço para sinais de aceleração.",
    strongConfidence: 70,
    weakConfidence: 45,
    period: 12,
  },
  {
    id: "RVI_BOT_1",
    strategyType: "RVI",
    justification: "Mede a convicção da tendência com base no vigor relativo.",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 10,
    strongBuyThreshold: 40,
    weakBuyThreshold: 50,
    strongSellThreshold: 60,
    weakSellThreshold: 50,
  },
  {
    id: "SAR_BOT_1",
    strategyType: "PARABOLIC_SAR",
    justification: "Identifica reversões de tendência com pontos SAR.",
    strongConfidence: 85,
    weakConfidence: 60,
    acceleration: 0.02,
    maxAcceleration: 0.2,
  },
  // --- Volatility & Structure ---
  {
    id: "BOLLINGER_BOT_1",
    strategyType: "BOLLINGER_BANDS",
    justification: "Negocia com base em Bandas de Bollinger padrão (20/2.0) para 'squeezes'.",
    strongConfidence: 85,
    weakConfidence: 65,
    period: 20,
    stdDev: 2.0,
  },
  {
    id: "ICHIMOKU_BOT_1",
    strategyType: "ICHIMOKU_CLOUD",
    justification: "Analisa a nuvem Kumo como suporte/resistência dinâmica.",
    strongConfidence: 88,
    weakConfidence: 60,
  },
  {
    id: "KAMA_BOT_1",
    strategyType: "KAMA",
    justification: "Usa a média móvel adaptativa para seguir a tendência suavemente.",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 10,
    fastEnd: 2,
    slowEnd: 30,
  },
  {
    id: "DONCHIAN_BOT_1",
    strategyType: "DONCHIAN_CHANNELS",
    justification: "Busca rompimentos dos canais de Donchian de 20 períodos.",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 20,
  },
  {
    id: "CHANDELIER_BOT_1",
    strategyType: "CHANDELIER_EXIT",
    justification: "Usa o Chandelier Exit para seguir a tendência.",
    strongConfidence: 85,
    weakConfidence: 60,
    period: 22,
    multiplier: 3,
  },
  // --- Volume & Order Flow ---
  {
    id: "VOL_PROFILE_BOT_1",
    strategyType: "VOLUME_PROFILE",
    justification: "Identifica suporte/resistência em zonas de alto volume (POC).",
    strongConfidence: 75,
    weakConfidence: 50,
    profileBars: 100,
  },
  {
    id: "VWAP_BOT_1",
    strategyType: "VWAP",
    justification: "Usa o VWAP como um nível de preço médio dinâmico.",
    strongConfidence: 85,
    weakConfidence: 60,
  },
  {
    id: "MFI_BOT_1",
    strategyType: "MFI",
    justification: "RSI ponderado por volume para medir a pressão do dinheiro.",
    strongConfidence: 80,
    weakConfidence: 60,
    period: 14,
    strongBuyThreshold: 20,
    weakBuyThreshold: 30,
    strongSellThreshold: 80,
    weakSellThreshold: 70,
  },
  {
    id: "OBV_BOT_1",
    strategyType: "OBV",
    justification: "Confirma a força da tendência com base no volume acumulado.",
    strongConfidence: 75,
    weakConfidence: 50,
  },
  // --- Statistical & Mean Reversion ---
  {
    id: "ZSCORE_BOT_1",
    strategyType: "Z_SCORE",
    justification: "Negocia reversão à média com base em desvios padrão (Z-Score).",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 20,
    zScoreThreshold: 2.0,
  },
  {
    id: "STOCH_RSI_BOT_1",
    strategyType: "STOCH_RSI",
    justification: "Indicador de indicador para sinais rápidos de sobrecompra/venda.",
    strongConfidence: 90,
    weakConfidence: 70,
    period: 14,
    strongBuyThreshold: 0.20,
    weakBuyThreshold: 0.30,
    strongSellThreshold: 0.80,
    weakSellThreshold: 0.70,
  },
  // --- Patterns ---
  {
    id: "PRICE_ACTION_BOT_1",
    strategyType: "PRICE_ACTION_PATTERN",
    justification: "Identifica padrões de velas de reversão como Martelo/Estrela Cadente.",
    strongConfidence: 95,
    weakConfidence: 75,
    pattern: "hammer",
  },
  // --- Moving Average ---
  {
    id: "MA_CROSS_BOT_1",
    strategyType: "MOVING_AVERAGE_CROSS",
    justification: "Cruzamento de médias médios (10/20) para suporte dinâmico.",
    strongConfidence: 78,
    weakConfidence: 52,
    shortPeriod: 10,
    longPeriod: 20,
  }
];
