// src/features/trading/services/council-strategies.ts
import type { RobotStrategy } from '@/lib/types';

// This file contains the pre-defined, local configuration for the 22 robot analysts.
// Each robot now has its own optimal duration and unit, making the system's time-based decisions dynamic.

export const initialCouncilStrategies: Omit<RobotStrategy, 'id' | 'justification'>[] = [
  // --- Momentum & Trend (Short-Term Specialists) ---
  {
    strategyType: "RSI",
    strongConfidence: 90,
    weakConfidence: 60,
    period: 10,
    strongBuyThreshold: 25,
    weakBuyThreshold: 35,
    strongSellThreshold: 75,
    weakSellThreshold: 65,
    optimalDuration: 5,
    optimalDurationUnit: 't',
    suggestedStake: 1.5,
  },
  {
    strategyType: "STOCHASTIC",
    strongConfidence: 90,
    weakConfidence: 70,
    period: 14,
    strongBuyThreshold: 20,
    weakBuyThreshold: 30,
    strongSellThreshold: 80,
    weakSellThreshold: 70,
    optimalDuration: 5,
    optimalDurationUnit: 't',
    suggestedStake: 1.5,
  },
  {
    strategyType: "MACD_CROSS",
    strongConfidence: 80,
    weakConfidence: 50,
    fastPeriod: 12,
    slowPeriod: 26,
    signalPeriod: 9,
    optimalDuration: 2,
    optimalDurationUnit: 'm',
    suggestedStake: 1.0,
  },
  {
    strategyType: "ADX_TREND",
    strongConfidence: 85,
    weakConfidence: 60,
    period: 14,
    trendStrengthThreshold: 25,
    optimalDuration: 3,
    optimalDurationUnit: 'm',
    suggestedStake: 1.2,
  },
  {
    strategyType: "AWESOME_OSCILLATOR",
    strongConfidence: 75,
    weakConfidence: 50,
    optimalDuration: 1,
    optimalDurationUnit: 'm',
    suggestedStake: 0.8,
  },
  {
    strategyType: "TRIX",
    strongConfidence: 70,
    weakConfidence: 45,
    period: 15,
    optimalDuration: 2,
    optimalDurationUnit: 'm',
    suggestedStake: 0.7,
  },
  {
    strategyType: "ROC",
    strongConfidence: 70,
    weakConfidence: 45,
    period: 12,
    optimalDuration: 45,
    optimalDurationUnit: 's',
    suggestedStake: 0.9,
  },
  {
    strategyType: "RVI",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 10,
    strongBuyThreshold: 40,
    weakBuyThreshold: 50,
    strongSellThreshold: 60,
    weakSellThreshold: 50,
    optimalDuration: 1,
    optimalDurationUnit: 'm',
    suggestedStake: 1.0,
  },
  {
    strategyType: "PARABOLIC_SAR",
    strongConfidence: 85,
    weakConfidence: 60,
    acceleration: 0.02,
    maxAcceleration: 0.2,
    optimalDuration: 10,
    optimalDurationUnit: 't',
    suggestedStake: 1.3,
  },
  // --- Volatility & Structure ---
  {
    strategyType: "BOLLINGER_BANDS",
    strongConfidence: 85,
    weakConfidence: 65,
    period: 20,
    stdDev: 2.0,
    optimalDuration: 7,
    optimalDurationUnit: 't',
    suggestedStake: 1.4,
  },
  {
    strategyType: "ICHIMOKU_CLOUD",
    strongConfidence: 88,
    weakConfidence: 60,
    optimalDuration: 5,
    optimalDurationUnit: 'm',
    suggestedStake: 1.5,
  },
  {
    strategyType: "KAMA",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 10,
    fastEnd: 2,
    slowEnd: 30,
    optimalDuration: 3,
    optimalDurationUnit: 'm',
    suggestedStake: 1.1,
  },
  {
    strategyType: "DONCHIAN_CHANNELS",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 20,
    optimalDuration: 1,
    optimalDurationUnit: 'm',
    suggestedStake: 1.0,
  },
  {
    strategyType: "CHANDELIER_EXIT",
    strongConfidence: 85,
    weakConfidence: 60,
    period: 22,
    multiplier: 3,
    optimalDuration: 2,
    optimalDurationUnit: 'm',
    suggestedStake: 1.2,
  },
  // --- Volume & Order Flow ---
  {
    strategyType: "VOLUME_PROFILE",
    strongConfidence: 75,
    weakConfidence: 50,
    profileBars: 100,
    optimalDuration: 5,
    optimalDurationUnit: 'm',
    suggestedStake: 0.9,
  },
  {
    strategyType: "VWAP",
    strongConfidence: 85,
    weakConfidence: 60,
    optimalDuration: 1,
    optimalDurationUnit: 'm',
    suggestedStake: 1.3,
  },
  {
    strategyType: "MFI",
    strongConfidence: 80,
    weakConfidence: 60,
    period: 14,
    strongBuyThreshold: 20,
    weakBuyThreshold: 30,
    strongSellThreshold: 80,
    weakSellThreshold: 70,
    optimalDuration: 5,
    optimalDurationUnit: 't',
    suggestedStake: 1.2,
  },
  {
    strategyType: "OBV",
    strongConfidence: 75,
    weakConfidence: 50,
    optimalDuration: 2,
    optimalDurationUnit: 'm',
    suggestedStake: 0.8,
  },
  // --- Statistical & Mean Reversion ---
  {
    strategyType: "Z_SCORE",
    strongConfidence: 80,
    weakConfidence: 55,
    period: 20,
    zScoreThreshold: 2.0,
    optimalDuration: 7,
    optimalDurationUnit: 't',
    suggestedStake: 1.1,
  },
  {
    strategyType: "STOCH_RSI",
    strongConfidence: 90,
    weakConfidence: 70,
    period: 14,
    strongBuyThreshold: 0.20,
    weakBuyThreshold: 0.30,
    strongSellThreshold: 0.80,
    weakSellThreshold: 0.70,
    optimalDuration: 5,
    optimalDurationUnit: 't',
    suggestedStake: 1.4,
  },
  // --- Patterns ---
  {
    strategyType: "PRICE_ACTION_PATTERN",
    strongConfidence: 95,
    weakConfidence: 75,
    pattern: "hammer",
    optimalDuration: 5,
    optimalDurationUnit: 't',
    suggestedStake: 1.8,
  },
  // --- Moving Average ---
  {
    strategyType: "MOVING_AVERAGE_CROSS",
    strongConfidence: 78,
    weakConfidence: 52,
    shortPeriod: 10,
    longPeriod: 20,
    optimalDuration: 1,
    optimalDurationUnit: 'm',
    suggestedStake: 1.0,
  }
].map((strat, index) => ({
    ...strat,
    id: `${strat.strategyType}_BOT_${index + 1}`,
    justification: `Especialista em ${strat.strategyType} para o horizonte de tempo de {{timePeriod}}.`
}));
