'use server';

/**
 * @fileOverview A mock financial data service. In a real application, this would
 * fetch data from a database or a financial API.
 */
import type { Goal } from '@/lib/types';


// Mock database
const MOCK_DATA = {
    transactions: [
      { id: 1, date: "2024-08-01", description: "Salário", amount: 7250, type: "income" },
      { id: 2, date: "2024-08-01", description: "Aluguel", amount: 1800, type: "expense" },
      { id: 3, date: "2024-08-05", description: "Supermercado", amount: 850, type: "expense" },
      { id: 4, date: "2024-08-10", description: "Posto Shell", amount: 450, type: "expense" },
      { id: 5, date: "2024-08-12", description: "Cinema", amount: 600, type: "expense" },
      { id: 6, date: "2024-08-15", description: "Compras Online", amount: 780, type: "expense" },
      { id: 7, date: "2024-08-20", description: "Outros", amount: 350, type: "expense" },
    ],
    goals: [
        {
            id: "1",
            name: "Viagem para o Japão",
            currentAmount: 7500,
            targetAmount: 12000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "japan temple"
        },
        {
            id: "2",
            name: "Entrada da Casa Própria",
            currentAmount: 27500,
            targetAmount: 50000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "dream house"
        },
        {
            id: "3",
            name: "Fundo de Emergência",
            currentAmount: 8500,
            targetAmount: 10000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "saving money"
        },
        {
            id: "4",
            name: "Renovação da Cozinha",
            currentAmount: 2500,
            targetAmount: 15000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "modern kitchen"
        },
    ],
  };
  
  export async function getFinancialSummary(): Promise<string> {
    const income = MOCK_DATA.transactions
      .filter((t) => t.type === 'income')
      .reduce((acc, t) => acc + t.amount, 0);
  
    const expenses = MOCK_DATA.transactions
      .filter((t) => t.type === 'expense')
      .reduce((acc, t) => acc + t.amount, 0);
  
    const summary = `
      Resumo Financeiro:
      - Renda Mensal Total: R$${income.toFixed(2)}
      - Despesas Mensais Totais: R$${expenses.toFixed(2)}
      - Saldo: R$${(income - expenses).toFixed(2)}
    `;
    return summary;
  }
  
  export async function getInsights(): Promise<string[]> {
    // In a real scenario, this would be generated by an AI based on the data.
    // Here we use mock insights.
    return [
      "Você gastou R$150 em restaurantes. Tente cozinhar em casa para economizar.",
      "Sua maior despesa é o aluguel. Considere procurar opções mais baratas, se possível.",
      "Você está perto de atingir seu fundo de emergência! Continue assim."
    ];
  }
  
  export async function addTransaction(description: string, amount: number, type: 'income' | 'expense'): Promise<string> {
    const newId = MOCK_DATA.transactions.length + 1;
    MOCK_DATA.transactions.push({
      id: newId,
      date: new Date().toISOString().split('T')[0],
      description,
      amount,
      type,
    });
    console.log('Nova transação adicionada:', MOCK_DATA.transactions.at(-1));
    return `Transação "${description}" de R$${amount.toFixed(2)} adicionada com sucesso.`;
  }
  
  export async function addGoal(name: string, targetAmount: number): Promise<Goal> {
    const newId = (MOCK_DATA.goals.length + 1).toString();
    const newGoal: Goal = {
      id: newId,
      name,
      targetAmount,
      currentAmount: 0,
      imageUrl: "https://placehold.co/600x400.png",
      imageHint: "new goal"
    };
    MOCK_DATA.goals.push(newGoal);
    console.log('Nova meta adicionada:', newGoal);
    return newGoal;
  }
  
  export async function getGoals(): Promise<Goal[]> {
      return MOCK_DATA.goals;
  }
  
