

'use server';

/**
 * @fileOverview A mock financial data service. In a real application, this would
 * fetch data from a database or a financial API.
 */
import type { Goal, BudgetCategory } from '@/lib/types';
import { generateGoalImage } from '@/ai/flows/goal-image-generation';


// Mock database
const MOCK_DATA = {
    transactions: [
      { id: 1, date: "2024-08-01", description: "Salário", amount: 7250, type: "income", category: "Renda" },
      { id: 2, date: "2024-08-01", description: "Aluguel", amount: 1800, type: "expense", category: "Moradia" },
      { id: 3, date: "2024-08-05", description: "Supermercado", amount: 850, type: "expense", category: "Alimentação" },
      { id: 4, date: "2024-08-10", description: "Gasolina", amount: 300, type: "expense", category: "Transporte" },
      { id: 10, date: "2024-08-18", description: "Uber", amount: 150, type: "expense", category: "Transporte" },
      { id: 5, date: "2024-08-12", description: "Cinema", amount: 600, type: "expense", category: "Lazer" },
      { id: 6, date: "2024-08-15", description: "Compras Online", amount: 780, type: "expense", category: "Compras" },
      { id: 7, date: "2024-08-20", description: "Farmácia", amount: 150, type: "expense", category: "Outros" },
      { id: 8, date: "2024-08-22", description: "Padaria", amount: 200, type: "expense", category: "Alimentação" },
    ],
    goals: [
        {
            id: "1",
            name: "Viagem para o Japão",
            currentAmount: 7500,
            targetAmount: 12000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "japan temple"
        },
        {
            id: "2",
            name: "Entrada da Casa Própria",
            currentAmount: 27500,
            targetAmount: 50000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "dream house"
        },
        {
            id: "3",
            name: "Fundo de Emergência",
            currentAmount: 8500,
            targetAmount: 10000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "saving money"
        },
        {
            id: "4",
            name: "Renovação da Cozinha",
            currentAmount: 2500,
            targetAmount: 15000,
            imageUrl: "https://placehold.co/600x400.png",
            imageHint: "modern kitchen"
        },
    ],
    budgetLimits: {
        "Moradia": 2000,
        "Alimentação": 1000,
        "Transporte": 500,
        "Lazer": 400,
        "Compras": 600,
        "Outros": 300,
    }
  };
  
  export async function getFinancialSummary(): Promise<{ income: number; expenses: number; balance: number; }> {
    const income = MOCK_DATA.transactions
      .filter((t) => t.type === 'income')
      .reduce((acc, t) => acc + t.amount, 0);
  
    const expenses = MOCK_DATA.transactions
      .filter((t) => t.type === 'expense')
      .reduce((acc, t) => acc + t.amount, 0);
  
    return {
        income,
        expenses,
        balance: income - expenses,
    }
  }
  
  export async function getInsights(): Promise<string[]> {
    // In a real scenario, this would be generated by an AI based on the data.
    // Here we use mock insights.
    return [
      "Você gastou R$150 em restaurantes. Tente cozinhar em casa para economizar.",
      "Sua maior despesa é o aluguel. Considere procurar opções mais baratas, se possível.",
      "Você está perto de atingir seu fundo de emergência! Continue assim."
    ];
  }
  
  export async function addTransaction(description: string, amount: number, type: 'income' | 'expense'): Promise<string> {
    const newId = MOCK_DATA.transactions.length + 1;
    MOCK_DATA.transactions.push({
      id: newId,
      date: new Date().toISOString().split('T')[0],
      description,
      amount,
      type,
      category: "Outros"
    });
    console.log('Nova transação adicionada:', MOCK_DATA.transactions.at(-1));
    return `Transação "${description}" de R$${amount.toFixed(2)} adicionada com sucesso.`;
  }
  
  export async function addGoal(name: string, targetAmount: number): Promise<Goal> {
    const newId = Date.now().toString();
    
    let imageUrl = "https://placehold.co/600x400.png";
    try {
        const imageResult = await generateGoalImage({ goalName: name });
        imageUrl = imageResult.imageUrl;
    } catch (error) {
        console.error("Falha ao gerar imagem da meta, usando placeholder.", error);
    }

    const newGoal: Goal = {
      id: newId,
      name,
      targetAmount,
      currentAmount: 0,
      imageUrl: imageUrl,
      imageHint: "new goal"
    };
    MOCK_DATA.goals.push(newGoal);
    console.log('Nova meta adicionada:', newGoal);
    return newGoal;
  }
  
  export async function getGoals(): Promise<Goal[]> {
      return MOCK_DATA.goals;
  }

  export async function deleteGoal(goalId: string): Promise<{ success: boolean }> {
    const initialLength = MOCK_DATA.goals.length;
    MOCK_DATA.goals = MOCK_DATA.goals.filter(goal => goal.id !== goalId);
    const success = MOCK_DATA.goals.length < initialLength;
    if(success) {
        console.log(`Meta com ID ${goalId} deletada.`);
    } else {
        console.warn(`Meta com ID ${goalId} não encontrada para deletar.`);
    }
    return { success };
  }

  export async function getBudgetData(): Promise<BudgetCategory[]> {
    const expensesByCategory = MOCK_DATA.transactions
      .filter(t => t.type === 'expense')
      .reduce((acc, t) => {
        const category = t.category || "Outros";
        if (!acc[category]) {
          acc[category] = 0;
        }
        acc[category] += t.amount;
        return acc;
      }, {} as { [key: string]: number });
  
    const budgetData = Object.entries(MOCK_DATA.budgetLimits).map(([name, budgeted]) => ({
      name,
      budgeted,
      spent: expensesByCategory[name] || 0,
    }));
    
    await new Promise(resolve => setTimeout(resolve, 500));
    return budgetData;
  }

  export async function updateBudgetLimit(name: string, newLimit: number): Promise<BudgetCategory | null> {
    if (name in MOCK_DATA.budgetLimits) {
      MOCK_DATA.budgetLimits[name as keyof typeof MOCK_DATA.budgetLimits] = newLimit;
      console.log(`Limite do orçamento para "${name}" atualizado para ${newLimit}`);
      
      const expensesByCategory = MOCK_DATA.transactions
        .filter(t => t.type === 'expense' && t.category === name)
        .reduce((sum, t) => sum + t.amount, 0);

      return {
        name,
        budgeted: newLimit,
        spent: expensesByCategory,
      };
    }
    console.warn(`Categoria de orçamento "${name}" não encontrada para atualização.`);
    return null;
  }
