/**
 * @fileOverview A mock financial data service. In a real application, this would
 * fetch data from a database or a financial API.
 */

// Mock database
const MOCK_DATA = {
    transactions: [
      { id: 1, date: "2024-08-01", description: "Salário", amount: 5000, type: "income" },
      { id: 2, date: "2024-08-01", description: "Aluguel", amount: 1500, type: "expense" },
      { id: 3, date: "2024-08-05", description: "Supermercado", amount: 400, type: "expense" },
      { id: 4, date: "2024-08-10", description: "Restaurante", amount: 150, type: "expense" },
      { id: 5, date: "2024-08-15", description: "Conta de Luz", amount: 120, type: "expense" },
    ],
    goals: [
      { id: 1, name: "Viagem para o Japão", target: 12000, current: 7500 },
      { id: 2, name: "Fundo de Emergência", target: 10000, current: 8500 },
    ],
  };
  
  export function getFinancialSummary(): string {
    const income = MOCK_DATA.transactions
      .filter((t) => t.type === 'income')
      .reduce((acc, t) => acc + t.amount, 0);
  
    const expenses = MOCK_DATA.transactions
      .filter((t) => t.type === 'expense')
      .reduce((acc, t) => acc + t.amount, 0);
  
    const summary = `
      Resumo Financeiro:
      - Renda Mensal Total: R$${income.toFixed(2)}
      - Despesas Mensais Totais: R$${expenses.toFixed(2)}
      - Saldo: R$${(income - expenses).toFixed(2)}
    `;
    return summary;
  }
  
  export function getInsights(): string[] {
    // In a real scenario, this would be generated by an AI based on the data.
    // Here we use mock insights.
    return [
      "Você gastou R$150 em restaurantes. Tente cozinhar em casa para economizar.",
      "Sua maior despesa é o aluguel. Considere procurar opções mais baratas, se possível.",
      "Você está perto de atingir seu fundo de emergência! Continue assim."
    ];
  }
  
  export function addTransaction(description: string, amount: number, type: 'income' | 'expense'): string {
    const newId = MOCK_DATA.transactions.length + 1;
    MOCK_DATA.transactions.push({
      id: newId,
      date: new Date().toISOString().split('T')[0],
      description,
      amount,
      type,
    });
    return `Transação "${description}" de R$${amount.toFixed(2)} adicionada com sucesso.`;
  }
  
  export function addGoal(name: string, target: number): string {
    const newId = MOCK_DATA.goals.length + 1;
    MOCK_DATA.goals.push({
      id: newId,
      name,
      target,
      current: 0,
    });
    return `Meta "${name}" de R$${target.toFixed(2)} adicionada com sucesso.`;
  }
  
